apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
stringData:
  mysql-root-password: "Ch@ngeme123"
  mysql-password: "Wp@ssword123"
  mysql-database: "wordpressdb"
  mysql-user: "wpuser"
